name: Trigger Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Selenium Repo Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SELENIUM_REPO_PAT }}
          repository: logangarbacki/react-portfolio-selenium-tests
          event-type: run-selenium-tests